/**
 * User Email Templates Mock Data
 * All mock data for email template previews
 */

import { UserEmailTemplate } from '@/types/template';

/**
 * System Email Templates
 */
export const MOCK_SYSTEM_TEMPLATES: UserEmailTemplate[] = [
  {
    id: 'welcome-email',
    name: 'Welcome Email',
    category: 'system',
    icon: 'shield',
    from: 'PhishGuard',
    fromEmail: 'welcome@phishguard.com',
    subject: 'Welcome to PhishGuard',
    body: `Hello DanielRex,

Thanks for joining us!

Thanks for joining PhishGuard, your shield against phishing and spam messages.
We bring you quizzes, resources, and templates, to help you understand and recognize phishing and spam messages.

What to expect
- You will receive simulated phishing emails periodically.
- These are safe, controlled training exercises.
- If you click a suspicious link, you'll be guided through a short learning experience.

Thanks,
The PhishGuard Team`,
    buttonText: 'Download PhishGuard',
    footerText: 'This email is auto-generated by PhishGuard. Do not reply.\nYou are receiving this email because you signed up to PhishGuard.',
    footerCompany: 'PhishGuard Pty Ltd, 110 Kanasas St, New Jersey, 2010, Australia. ABN 20 238 859 794\nIf you need assistance, get in touch with us via our Help Centre.',
    footerLinks: [
      { text: 'Visit PhishGuard', url: '#' },
      { text: 'Unsubscribe', url: '#' },
      { text: 'Manage Email Preferences', url: '#' }
    ],
    footerCopyright: '© 2025 PhishGuard'
  },
  {
    id: 'password-reset-system',
    name: 'Password Reset',
    category: 'system',
    icon: 'key',
    from: 'PhishGuard',
    fromEmail: 'noreply@phishguard.com',
    subject: 'Your password was reset',
    body: `Hello DanielRex,

We wanted to let you know that your PhishGuard password was reset.

If you did not perform this action, you can recover access by entering danielrex@gmail.com into the form at https://phishguard.com/password_reset

To secure your account, follow the steps outlined by https://docs.phishguard.com/articles/preventing-unauthorized-access

To see this and other security events for your account, visit https://phishguard.com/settings/security-log

If you run into problems, please contact support by visiting https://phishguard.com/contact

Please do not reply to this email with your password. We will never ask for your password, and we strongly discourage you from sharing it with anyone.`,
    footerText: 'This email is auto-generated by PhishGuard. Do not reply.\nYou are receiving this email because you signed up to PhishGuard.',
    footerCompany: 'PhishGuard Pty Ltd, 110 Kanasas St, New Jersey, 2010, Australia. ABN 20 238 859 794\nIf you need assistance, get in touch with us via our Help Centre.',
    footerLinks: [
      { text: 'Visit PhishGuard', url: '#' },
      { text: 'Unsubscribe', url: '#' },
      { text: 'Manage Email Preferences', url: '#' }
    ],
    footerCopyright: '© 2025 PhishGuard'
  },
  {
    id: 'campaign-results',
    name: 'Campaign Results Summary',
    category: 'system',
    icon: 'clipboard',
    from: 'PhishGuard',
    fromEmail: 'reports@phishguard.com',
    subject: 'Campaign Results Summary',
    body: `Hello Admin,

Your recent phishing simulation campaign has been completed.

Campaign: Q4 Security Awareness
Duration: Dec 1 - Dec 15, 2024
Participants: 250 employees

Results:
- Click Rate: 18%
- Reported: 45%
- Training Completed: 89%

View the full report in your dashboard.

Thanks,
The PhishGuard Team`,
    buttonText: 'View Full Report',
    footerText: 'This email is auto-generated by PhishGuard. Do not reply.',
    footerCompany: 'PhishGuard Pty Ltd, 110 Kanasas St, New Jersey, 2010, Australia.',
    footerCopyright: '© 2025 PhishGuard'
  }
];

/**
 * Phishing Email Templates
 */
export const MOCK_PHISHING_TEMPLATES: UserEmailTemplate[] = [
  {
    id: 'password-reset-phishing',
    name: 'Password Reset',
    category: 'phishing',
    icon: 'lock',
    from: 'IT Security Team',
    fromEmail: 'security@compamy-it.com',
    subject: 'Your Password Will Expire Today',
    body: `Dear User,

We detected unusual activity on your account and have reset your password for security reasons.

To regain access, please reset your password immediately.

If you do not reset your password within the next 2 hours, your account will be locked.

Thank you,
IT Security Team`,
    buttonText: 'RESET PASSWORD NOW',
    footerText: 'Please do not reply. You are receiving this email because you subscribed to IT Security.',
    footerCompany: 'Questions? Contact security@compamy-it.com',
    footerCopyright: '© 2025 IT Security Team'
  },
  {
    id: 'hr-announcement',
    name: 'HR Announcement',
    category: 'phishing',
    icon: 'user',
    from: 'HR Department',
    fromEmail: 'hr@compamy.com',
    subject: 'Immediate view Required: Updated Company Policies',
    body: `Dear Esteemed Team Member,

We have updated our internal policies effective immediately.
You are required to review the new document and sign acknowledgment.

Please click the link below:
https://company.com/verify-account

Failure to complete this within 24 hours will result in administrative review.

Thank you,
HR Department`,
    footerText: 'Please do not reply. You are receiving this email because you are a part of our company.',
    footerCompany: 'Questions? Contact hr@compamy.com',
    footerCopyright: '© 2025 HR Department | Company Inc'
  },
  {
    id: 'package-delivery',
    name: 'Package Delivery',
    category: 'phishing',
    icon: 'package',
    from: 'Delivery Service',
    fromEmail: 'notifications@shippexpress.com',
    subject: 'Your Package Delivery Failed — Action Needed',
    body: `Hello,

We attempted to deliver your package today, but no one was available.

To reschedule your delivery, please confirm your details:
Tracking Code: PKG-8B3120X

Failure to complete this within 24 hours will result in administrative review.

Thank you,
Shippexpress Delivery Team`,
    footerText: 'Please do not reply.',
    footerCompany: 'Questions? Contact notifications@shippexpress.com',
    footerCopyright: '© 2025 Shippexpress'
  },
  {
    id: 'bank-alert',
    name: 'Bank Alert',
    category: 'phishing',
    icon: 'credit',
    from: 'Bank Security',
    fromEmail: 'alerts@security-bnk.com',
    subject: 'Unusual Login Attempt Detected on Your Account',
    body: `Dear Customer,

We detected an unusual login attempt from Lagos, Nigeria. Your account has been temporarily restricted.

To verify your identity, click the 'verify my account' button below.
If this is not resolved within 1 hour, your account will be permanently restricted.

Thank you,
Bank Security Team`,
    buttonText: 'VERIFY MY ACCOUNT',
    footerText: 'Please do not reply.',
    footerCompany: 'Questions? Contact alerts@security-bnk.com',
    footerCopyright: '© 2025 Bank Security'
  },
  {
    id: 'it-support',
    name: 'IT Support',
    category: 'phishing',
    icon: 'wrench',
    from: 'IT Admin',
    fromEmail: 'admin@support-update.com',
    subject: 'Unusual Login Attempt Detected on Your Account',
    body: `Hello,

Our system is undergoing an upgrade. Please confirm your account information to avoid service interruption.

This process should take less than 1 minute

Thank you,
Bank Security Team`,
    buttonText: 'CONFIRM',
    footerText: 'Please do not reply.',
    footerCompany: 'Questions? Contact admin@support-update.com',
    footerCopyright: '© 2025 IT Administration | Technical Support'
  },
  {
    id: 'social-media',
    name: 'Social Media Notification',
    category: 'phishing',
    icon: 'share',
    from: 'Security Alert',
    fromEmail: 'no-reply@instagrm-security.com',
    subject: 'Unauthorized Log in',
    body: `Hello,

Your account was accessed from a new device.
If this wasn't you, secure your account: by clocking the button below.

Thank you,
The Instagram Team`,
    buttonText: 'SECURE MY ACCOUNT',
    footerText: 'Please do not reply.',
    footerCompany: 'Questions? Contact no-reply@instagrm-security.com',
    footerCopyright: '© 2025 Instagram'
  }
];

/**
 * All User Templates
 */
export const MOCK_ALL_USER_TEMPLATES = [
  ...MOCK_SYSTEM_TEMPLATES,
  ...MOCK_PHISHING_TEMPLATES
];

/**
 * Helper: Get templates by category
 */
export const getUserTemplatesByCategory = (category: 'phishing' | 'system') => {
  return category === 'phishing' ? MOCK_PHISHING_TEMPLATES : MOCK_SYSTEM_TEMPLATES;
};

export const getUserTemplateById = (id: string) => {
  return MOCK_ALL_USER_TEMPLATES.find(template => template.id === id);
};